spring:
  application:
    name: vehicle-service

  datasource:
    url: jdbc:mysql://localhost:3306/automotives
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: health

datasource:
